In [26]:
import numpy as np

print(np.arange(0,10,1))                  #1
print(np.linspace(0,9,10,True,True,int), '\n')

print(np.arange(1,13,2))                  #2
print(np.linspace(1,13,7,True,True,int), '\n')

a=np.zeros((1,10),dtype=int)              #3
a[0,5]=11
print(a, '\n')

b=np.zeros((5,5),dtype=int)               #4
for i in range(5):
    b[0,i]=1
    b[i,0]=1
    b[4,i]=1
    b[i,4]=1
    
print(b)

[0 1 2 3 4 5 6 7 8 9]
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 1.0) 

[ 1  3  5  7  9 11]
(array([ 1,  3,  5,  7,  9, 11, 13]), 2.0) 

[[ 0  0  0  0  0 11  0  0  0  0]] 

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
