In [18]:
import numpy as np
import random as ran

u=np.arange(2.,100.,5)
print('u=',u, '\n')

for i in range(len(u)):
    if i%2==0:
        u[i]=np.inf

print("u'=",u, '\n')

print(np.isfinite(u), '\n')

N=int(input('Quanti "5" desideri nel tuo array? '))
print(np.dot(np.ones(N,dtype=int),5),'\n')

M=int(input("Quale ordine desideri per la tua matrice identica? "))
print(np.identity(M,dtype=int),'\n')

N=int(input('Quale ordine desideri per il tuo array? '))
n=int(11*ran.random())
print(np.dot(np.ones(N,dtype=int),n))

u= [ 2.  7. 12. 17. 22. 27. 32. 37. 42. 47. 52. 57. 62. 67. 72. 77. 82. 87.
 92. 97.] 

u'= [inf  7. inf 17. inf 27. inf 37. inf 47. inf 57. inf 67. inf 77. inf 87.
 inf 97.] 

[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True] 

Quanti "5" desideri nel tuo array? 3
[5 5 5] 

Quale ordine desideri per la tua matrice identica? 9
[[1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1]] 

Quale ordine desideri per il tuo array? 20
[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
