In [2]:
import numpy as np
import random as ran

v=np.arange(4,11)              #1
print('v =',v,'\n')
v.resize(2,4)
print("v' =\n",v,'\n')

u=np.arange(2,11)              #2
print('u =',u,'\n')
u.resize(3,3)
print("u' = \n",u,'\n')

N=int(input('Inserisci N: '))  #3
M=int(input('Inserisci M: '))
I=np.ones((N,M),int)
print('\nI =\n',I,'\n')
print("L'ordine di I è: ",I.shape,'\n')

a=np.arange(100,201,10)        #4
print('a =',a,'\n')
a.resize(5,2)
print("a' = \n",a)

v = [ 4  5  6  7  8  9 10] 

v' =
 [[ 4  5  6  7]
 [ 8  9 10  0]] 

u = [ 2  3  4  5  6  7  8  9 10] 

u' = 
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]] 

Inserisci N: 3
Inserisci M: 6

I =
 [[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]] 

L'ordine di I è:  (3, 6) 

a = [100 110 120 130 140 150 160 170 180 190 200] 

a' = 
 [[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]
