In [10]:
import numpy as np

N=int(input('Quante righe desideri? '))
M=int(input('Quante colonne desideri? '))
print('Inserisci gli elementi della matrice:')

A=np.empty((N,M),float)
for i in range(N):
    for j in range(M):
        A[i,j]=input()
print('\n A = \n',A,'\n')

print('Inserisci gli elementi della colonna da aggiungere:')
C=np.empty((1,N),float)
for i in range(N):
    C[0,i]=input()
print('\n C = \n',C.T)

A=A.T
D=np.vstack((A,C))
D=D.T
print('\n La matrice A con la colonna aggiunta C è: D = \n',D)

Quante righe desideri? 3
Quante colonne desideri? 5
Inserisci gli elementi della matrice:
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15

 A = 
 [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]] 

Inserisci gli elementi della colonna da aggiungere:
50
100
150

 C = 
 [[ 50.]
 [100.]
 [150.]]

 La matrice A con la colonna aggiunta C è: D = 
 [[  1.   2.   3.   4.   5.  50.]
 [  6.   7.   8.   9.  10. 100.]
 [ 11.  12.  13.  14.  15. 150.]]
