In [13]:
import numpy as np

a=np.arange(1,13)
a.resize(4,3)
print('a = \n',a,'\n')
print('R3 =',a[2,:],'\n')
print('C2 =',a[:,1])

a = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

R3 = [7 8 9] 

C2 = [ 2  5  8 11]
