In [60]:
import numpy as np
L=1

def λ(n):
    return 2*L/(n+1)

def f(x,n):
    return x*(L-x)*np.sin(2/λ(n)*np.pi*x)

A=np.linspace(0,1,100)
B=np.empty((100,5),float)

for x in range(100):
    for n in range(5):
        B[x,n]=round( f(A[x],n), 8)
print('Segue la tabella dei valori assunti dalle funzioni: \n')
print('      n=1          n=2         n=3        n=4          n=5 \n')
print(B, '\n')

M=B.argmax(0)
m=B.argmin(0)
N=np.empty((1,5),float)
n=np.empty((1,5),float)

for i in range(5):
    N[0,i]=A[M[i]]
    n[0,i]=A[m[i]]

print('Segue la sequenza dei punti di massimo e minimo delle funzioni: \n\nx_M =',N,'\n\nx_m =',n)

Segue la tabella dei valori assunti dalle funzioni: 

      n=1          n=2         n=3        n=4          n=5 

[[ 0.          0.          0.          0.          0.        ]
 [ 0.00031725  0.00063417  0.00095046  0.0012658   0.00157985]
 [ 0.00125541  0.00250576  0.00374602  0.0049712   0.00617636]
 [ 0.0027932   0.0055611   0.00827864  0.01092121  0.01346487]
 [ 0.00490819  0.0097374   0.01440993  0.0188506   0.02298796]
 [ 0.00757684  0.01496334  0.02197393  0.02843248  0.03417674]
 [ 0.01077463  0.02115985  0.03078029  0.03928824  0.04637623]
 [ 0.01447607  0.02824078  0.04061773  0.05099871  0.05887358]
 [ 0.0186548   0.03611379  0.05125778  0.06311602  0.07092836]
 [ 0.02328368  0.04468106  0.06245864  0.0751762   0.08180342]
 [ 0.02833484  0.05384023  0.07396925  0.08671187  0.09079563]
 [ 0.03377977  0.0634852   0.08553337  0.09726496  0.09726496]
 [ 0.03958939  0.07350704  0.09689377  0.10639909  0.10066124]
 [ 0.04573414  0.08379487  0.10779624  0.11371122  0.10054738]
 [ 